"""add batteries and telemetry tables

Revision ID: b682f1e101a5
Revises:
Create Date: 2026-09-12

This is Roadmap step 1.5: the first real schema. It creates exactly the two
tables that step calls for -- `batteries` and `telemetry` -- matching the
Implementation Contract section 20 database schema contract column-for-column.
(`battery_current_state`, `predictions`, and `alerts` are real tables in the
Contract too, but they belong to later roadmap steps -- 2.1, 4.5, and 3.3
respectively -- so they aren't created here.)

Written by hand rather than via `alembic revision --autogenerate`, because
autogenerate needs a live database connection to diff against, and this is
still just Python + SQLAlchemy metadata: for a brand-new first migration like
this one, a hand-written migration and an autogenerated one produce the exact
same result. `alembic upgrade head` is what actually needs a real, reachable
PostgreSQL database -- that verification step happens outside this file.
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b682f1e101a5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "batteries",
        sa.Column("battery_id", sa.String(length=32), primary_key=True),
        sa.Column("capacity_kwh", sa.Double(), nullable=False),
        sa.Column("max_power_kw", sa.Double(), nullable=False),
        sa.Column("nominal_voltage", sa.Double(), nullable=False),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("installation_date", sa.Date(), nullable=True),
        sa.Column("profile_type", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "telemetry",
        sa.Column("event_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "battery_id",
            sa.String(length=32),
            sa.ForeignKey("batteries.battery_id"),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state_of_charge", sa.Double(), nullable=False),
        sa.Column("voltage", sa.Double(), nullable=False),
        sa.Column("current", sa.Double(), nullable=False),
        sa.Column("power_kw", sa.Double(), nullable=False),
        sa.Column("temperature_c", sa.Double(), nullable=False),
        sa.Column("health_percent", sa.Double(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
    )

    # Contract section 20's required index -- fast "most recent readings for
    # this battery" lookups, the dashboard's most common query pattern later on.
    op.create_index(
        "ix_telemetry_battery_id_timestamp_desc",
        "telemetry",
        ["battery_id", sa.text("timestamp DESC")],
    )


def downgrade() -> None:
    op.drop_index("ix_telemetry_battery_id_timestamp_desc", table_name="telemetry")
    op.drop_table("telemetry")
    op.drop_table("batteries")
